# Generated by Django 5.2.4 on 2025-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_name_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PRO', 'Pro')], default='FREE', max_length=10),
        ),
    ]
