# Generated by Django 5.1.7 on 2025-04-06 13:56

import apiapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apiapp.models.CustomUserManager()),
            ],
        ),
    ]
